name: Release Desktop App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.event.inputs.version || github.ref_name }}
          releaseName: 'BettingTracker ${{ github.event.inputs.version || github.ref_name }}'
          releaseBody: |
            🎉 New release of BettingTracker!
            
            **Downloads:**
            - **BettingTracker-${{ github.event.inputs.version || github.ref_name }}-x64.msi** - Windows Installer (Recommended)
            - **BettingTracker-${{ github.event.inputs.version || github.ref_name }}-x64.exe** - Windows Executable
            
            **Installation:**
            1. Download the MSI file (recommended) or EXE file
            2. Run the installer
            3. Follow the installation wizard
            
            **What's new:**
            - Desktop application for Windows
            - Offline support
            - Native performance
            
            For web version, visit: https://jonte-jpg.github.io/betting-tracker
          releaseDraft: false
          prerelease: false
          includeDebug: false
          includeRelease: true
